### ISSUE TITLE
3D viewer: select proximity not working (for 1dth)

### ISSUE THREAD

**Issue by aschafu** [ODonoghueLab/Aquaria#1]
The "select proximity" menu entry (under Edit) does not select anything.

Example: Got to http://aquaria.ws/P15167/1dth/A , apply View -> Ligand Binding Sites, choose a ligand atom, then choose Edit -> "Select Proximity"
Result: This will entirely lose the selection (as you can verify with eg. ^C)
Expected Result: all residues within 6A of the ligand atom should be selected

**Comment by Traksewt** [comment]
This seems to work correctly for other structures, e.g. http://aquaria.ws/P04637/3q01/A . Investigating.

**Comment by Traksewt** [comment]
temp workaround: goto view -> show water
and check it.

**Comment by Traksewt** [comment]
fixed in v1.0.00001

**Comment by Traksewt** [comment]
![image](https://cloud.githubusercontent.com/assets/1939990/6099760/94393340-b055-11e4-85de-cec28b62f842.png)
