### ISSUE TITLE
3D viewer: Binding site view not showing neighbour side chains

### ISSUE THREAD

**Issue by aschafu** [ODonoghueLab/Aquaria#2]
To be more useful, the binding site view should show the side chains of the residues surrounding the ligands in lines representation. (I believe this is what has been shown in the past.) However, this does not happen any more. -- This is probably related to the other issue I just posted: Select Proximity is not working (https://github.com/ODonoghueLab/Aquaria/issues/1).

**Comment by Traksewt** [comment]
Dup of #1   Selecting between chains works for p53:
![image](https://cloud.githubusercontent.com/assets/1939990/6071568/659bbc04-adeb-11e4-96cb-ddee4d7342dd.png)
